language: java
branches:
  only:
  - master
before_install:
- curl --silent https://shunit2.googlecode.com/files/shunit2-2.1.6.tgz | tar xz -C
  /tmp/
- git clone https://github.com/heroku/heroku-buildpack-testrunner.git /tmp/testrunner
- "./etc/hatchet_travis_setup.sh"
install: true
script: eval $TEST_CMD
after_script: heroku keys:remove $USER@`hostname`
env:
  global:
  - HATCHET_RETRIES=3
  - HATCHET_DEPLOY_STRATEGY=git
  - HATCHET_BUILDPACK_BASE="https://github.com/heroku/heroku-buildpack-java.git"
  - HATCHET_APP_LIMIT=2
  - SHUNIT_HOME="/tmp/shunit2-2.1.6"
  - secure: Yw+/6Ad1SGNfTNfmU3OrAVDqVIy/x23CJ1SWUiwp3BAP3pJdhDKN5PbhTgtVq6PF05qCWUSqLs9JFnyIPgmKpwrxdJC2tmR7cBMJa2G1zJEsNGFFzTtnmr7R5xg2xubLNWB9ScLBYeTE1m93Mw4Ug9XPfgOWiens4wLf33/Hmuc=
  matrix:
  - TEST_CMD='mvn verify'
  - TEST_CMD="/tmp/testrunner/bin/run -c ."
